name: CI Maven project1
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  label:
    types:
      - created
  push:
    branches:
      - main
  pull_request:
    branches:
      - main        
jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - name: github repo checkout
        uses: actions/checkout@v3
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: build with maven
        run: |
          mvn -B package --file pom.xml
          mkdir artifacts && cp target/*.jar artifacts
          cd artifacts && ls    
      - name: Set up Node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install Snyk CLI
        run: npm install -g snyk
      - name: snyk auth
        run: snyk auth '5b8d1070-a1f0-4340-8e32-7af35f913e6e'
     
        
      - name: SYNK monitor
        run: snyk monitor
        

      - name: run Snyk Open Source Test
        run: snyk test
        
      - name: run Snyk Code Test
        run: snyk code test
       
      - name: save artifacts
        uses: actions/upload-artifact@v3  
        with:
          name: github-actions-artifacts
          path: artifacts
