name: CI Maven project
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  label:
    types:
      - created
  push:
    branches:
      - main
  pull_request:
    branches:
      - main        
jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - name: github repo checkout
        uses: actions/checkout@v3
      - name: setup jdk 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: build with maven
        run: |
          mvn -B package --file pom.xml
          mkdir artifacts && cp target/*.jar artifacts
          cd artifacts && ls
      - name: save artifacts
        uses: actions/upload-artifact@v3  
        with:
          name: github-actions-artifacts
          path: artifacts
